import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../config/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  searchContainer: {
    position: 'absolute',
    top: 50, 
    left: 20,
    right: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 28, 
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20, 
    height: 55,
    elevation: 5, 
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    zIndex: 1,
  },
  searchIcon: {
    marginRight: 10,
    fontSize: 22,
    color: COLORS.primary, 
    fontWeight: 'bold',
    transform: [{ rotate: '-45deg' }], 
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333333',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    zIndex: 1, // Taake bottom nav map ke upar click ho sake
  },
  navItem: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  navText: {
    fontSize: 12,
    marginTop: 4,
    color: '#666666',
  },
  activeNavText: {
  fontSize: 12,
  marginTop: 4,
  color: COLORS.primary, 
  fontWeight: '600',
},
});